# Capítulo 8: Evaluación de variables ambientales

## Análisis de regresión

```{r modelo, fig.cap = "Modelo lineal con gráficos base"}
data(moscas)

modelo <- lm(Div_Shan ~ IHH, data = moscas)
summary(modelo)

plot(moscas$IHH, moscas$Div_Shan)
abline(modelo, col = "red")
```

```{r modelo-ggplot, fig.cap = "Modelo líneal usando ggplot"}
library(ggplot2)

ggplot(modelo$model, aes(x = IHH, y = Div_Shan)) +
  geom_ribbon(
    stat = "smooth",
    method = "lm",
    fill = "grey90"
  ) +
  geom_point(size = 2, color = "blue") +
  geom_smooth(
    method = "lm",
    color = "black",
    linewidth = 1,
    lineend = "round",
    se = FALSE
  ) +
  theme_classic()
```

## Análisis de correlación

```{r, fig.show = "hold", out.width = "50%", fig.cap = "Gráficos prueba de correlación"}
data(moscas)

matriz_cor <- cor(moscas)
matriz_cor

library(corrplot)

corrplot(matriz_cor, method = "circle")
corrplot(matriz_cor, method = "color")
```

```{r}
resultado_prueba <- cor.test(moscas$IHH, moscas$Div_Shan)
resultado_prueba
```

## Análisis de componentes principales (PCA)

```{r pca, fig.cap = ""}
library(factoextra)

data(moscas)

datos_estandarizados <- scale(moscas)

pca <- prcomp(datos_estandarizados, scale = TRUE)
summary(pca)

moscas$group <- sub(".*_([BUG]).*", "\\1", rownames(moscas))
moscas$group <- ifelse(
  moscas$group == "B", "Bosque",
  ifelse(moscas$group == "G", "Pastizal",
  ifelse(moscas$group == "U", "Urbano", NA))
)
fviz_pca_biplot(pca, label = "var", addEllipses = TRUE, ellipse.level = 0.95, habillage = moscas$group)

datos_proyectados <- predict(pca, newdata = datos_estandarizados)
datos_proyectados
```

## Análisis de correspondecia canónica (CCA)

```{r, fig.show = "hide"}
library(BiodiversityR)
library(ggplot2)

data(abundancia)
data(ambiente)

resultado_cca <- cca(abundancia$localidad ~ ., ambiente)
summary(resultado_cca)
anova(resultado_cca)

plot_cca <- plot(resultado_cca)
elipses_plot_cca <- ordiellipse(resultado_cca, ambiente$estado_conservacion)

# ---- Extracción de datos para graficar ----

sitios <- sites.long(plot_cca)
especies <- species.long(plot_cca)
multiplicador <- attr(plot_cca$biplot, "arrow.mul")
vectores <- data.frame(plot_cca$biplot * multiplicador, row.names(plot_cca$biplot))
colnames(vectores) <- c("axis1", "axis2", "labels")
elipses <- ordiellipse.long(elipses_plot_cca)
nombres_ejes <- axis.long(resultado_cca)
```

```{r}
# ---- Gráfico ----

ggplot() +
  xlab(nombres_ejes[1, "label"]) +
  ylab(nombres_ejes[2, "label"]) +
  scale_x_continuous(expand = c(0.2, 0.2)) +
  geom_vline(
    xintercept = c(0),
    color = "grey",
    linetype = 2,
    linewidth = 0.3
  ) +
  geom_hline(
    yintercept = c(0),
    color = "grey",
    linetype = 2,
    linewidth = 0.3
  ) +
  geom_point(
    data = especies,
    aes(x = axis1, y = axis2),
    size = 1
  ) +
  geom_path(
    data = elipses,
    aes(x = axis1, y = axis2, group = Grouping, color = Grouping)
  ) +
  scale_colour_manual(
    name = "",
    breaks = c("ECB", "ECI", "ECD"),
    labels = c("Conservado", "Intermedio", "Deteriorado"),
    values = c("green", "orange", "red")
  ) +
  geom_segment(
    data = vectores,
    aes(x = 0, y = 0, xend = axis1, yend = axis2),
    linewidth = 0.4, color = "blue",
    arrow = arrow(angle = 20, length = unit(1.5, "mm"), type = "closed")
  ) +
  geom_label(
    data = vectores,
    aes(x = axis1, y = axis2, label = labels, hjust = "outward", vjust = "outward"),
    fill = NA,
    label.size = NA,
    label.padding = unit(0.2, "lines"),
    color = "blue",
    size = 3
  ) +
  theme_classic() +
  theme(legend.position = "top")
```


## Test de Mantel en R

```{r}
library(BiodiversityR)
library(geosphere)

data(abundancia)
data(coords)

dist_abundancia <- vegdist(abundancia$localidad, method = "bray")
dist_geografica <- as.dist(distm(coords, fun = distHaversine))

resultado_mantel <- mantel(dist_abundancia, dist_geografica, method = "pearson", permutations = 9999)
resultado_mantel
```

```{r dispersion-mantel, fig.cap = "Gráfico de dispersión matrices de distancia"}
plot(as.matrix(dist_geografica), as.matrix(dist_abundancia))
```



