# Capítulo 5: Índices para medir la diversidad biológica

## Diversidad alfa

### Riqueza de especies

```{r}
library(datosEcoR)
library(BiodiversityR)

data(abundancia)
data(ambiente)

specpool(abundancia$localidad, ambiente$estado_conservacion)
```

### Índices basados en dominancia

```{r}
data(abundancia)

D <- diversityresult(abundancia$conservacion, index = "Simpson", method = "each site")
B <- diversityresult(abundancia$conservacion, index = "Berger", method = "each site")
iD <- diversityresult(abundancia$conservacion, index = "inverseSimpson", method = "each site")
indices_dom <- data.frame(D, iD, B)

knitr::kable(indices_dom, col.names = c("Simpson", "Inverso de Simpson", "Berger"))
```

### Índices basados en equidad

```{r}
H <- diversityresult(abundancia$conservacion, index = "Shannon", method = "each site")
JP <- H/log(specnumber(abundancia$conservacion))
indices_equi <- data.frame(H, JP)

knitr::kable(indices_equi, col.names = c("Shannon", "Pielou"))
```

## Diversidad beta

```{r}
library(betapart)

incidencia <- ifelse(abundancia$conservacion > 0, 1, 0)

betapart.core(incidencia)
```

### Beta partición en base Jaccard

```{r}
multi_jac <- beta.multi(incidencia, index.family = "jac")
multi_jac

dist_jac <- beta.pair(incidencia, index.family = "jac")
dist_jac
```

### Beta partición en base Sørensen

```{r}
multi_sor <- beta.multi(incidencia, index.family = "sor")
multi_sor

dist_sor <- beta.pair(incidencia, index.family = "sor")
multi_sor
```
